name: capsi_website
description: Capsi — messages and files, device to device.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
